// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pulse/Chat.tsx": () => import("../components/mockups/pulse/Chat.tsx"),
  "./components/mockups/pulse/Discover.tsx": () => import("../components/mockups/pulse/Discover.tsx"),
  "./components/mockups/pulse/Profile.tsx": () => import("../components/mockups/pulse/Profile.tsx"),
  "./components/mockups/pulse/Sparks.tsx": () => import("../components/mockups/pulse/Sparks.tsx")
};
